# This file was generated by GoReleaser. DO NOT EDIT.
cask "hrd" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2815f6d2fa7fee268688011c360df9c738b32de13b3739aa0739b6f9e91190a4"
      url "https://github.com/joshuadavidthomas/hrd/releases/download/v#{version}/hrd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e6f4bce3cece36f2e316c64933c914b322a989e17c7753a9bf355d019687791"
      url "https://github.com/joshuadavidthomas/hrd/releases/download/v#{version}/hrd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad114858a0c3502fb7d0a2574ec0c0af4c471d81a4be7b00e021cb3a7aa15332"
      url "https://github.com/joshuadavidthomas/hrd/releases/download/v#{version}/hrd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8704dea312e065d369234a075e4f7834fe3c8ed06952556779744af8c745f69d"
      url "https://github.com/joshuadavidthomas/hrd/releases/download/v#{version}/hrd_linux_arm64.tar.gz"
    end
  end

  name "hrd"
  desc "Manage local and sandboxed Herdr sessions"
  homepage "https://github.com/joshuadavidthomas/hrd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hrd"

  # No zap stanza required

end
