# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TsSkills < Formula
  desc "A private Agent Skills registry for your tailnet"
  homepage "https://github.com/joshuadavidthomas/ts-skills"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshuadavidthomas/ts-skills/releases/download/v0.1.0/ts-skills_darwin_amd64.tar.gz"
      sha256 "7b854e7e217128ed6b5c19ee4d7115215efd8eb9c3e2a6ccc26c39ca89fd953b"

      define_method(:install) do
        bin.install "ts-skills"
        bin.install "ts-skillsd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joshuadavidthomas/ts-skills/releases/download/v0.1.0/ts-skills_darwin_arm64.tar.gz"
      sha256 "39f0e7139ba82021ee7497e6027beb226dc2234aef853f4f29adc0ab1d591c33"

      define_method(:install) do
        bin.install "ts-skills"
        bin.install "ts-skillsd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshuadavidthomas/ts-skills/releases/download/v0.1.0/ts-skills_linux_amd64.tar.gz"
      sha256 "e06e956192d90a878820dc3e57dbe9e25b36c6a0a29b69151f96ba6fe42ecf85"
      define_method(:install) do
        bin.install "ts-skills"
        bin.install "ts-skillsd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshuadavidthomas/ts-skills/releases/download/v0.1.0/ts-skills_linux_arm64.tar.gz"
      sha256 "92b5476cd41b12548defe82a0adb2d4af72bc4f1aed0ebc1b574885e810b3229"
      define_method(:install) do
        bin.install "ts-skills"
        bin.install "ts-skillsd"
      end
    end
  end

  test do
    system "#{bin}/ts-skills", "version"
  end
end
